default_stages: [commit]
repos:
- repo: local
  hooks:
  - id: split
    name: Check that commits are split by project
    entry: python ./support/mesos-split.py
    language: python
    language_version: 'python3'
    stages: [commit]
    require_serial: true
  - id: license
    name: Check required license headers
    description: license
    language: python
    language_version: 'python3'
    entry: python ./support/check-license.py
    types: [text]
    files: '.*\.(cpp|hpp|py)$' # TODO(bbannier): also check shell scripts.
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
  - id: pylint
    args: ['--score=n', '--rcfile=support/pylint.config']
    files: '(support).*'
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.49.0
  hooks:
  - id: eslint
    args: ['-c', 'support/.eslintrc.js']
    exclude: '^(site/source/assets/js/|src/webui/assets/libs/)'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-executables-have-shebangs
